/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StrategyBuilderRouteImport } from './routes/strategy-builder'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignalAccuracyRouteImport } from './routes/signal-accuracy'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ReleaseNotesRouteImport } from './routes/release-notes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OptionsChainRouteImport } from './routes/options-chain'
import { Route as OptionsAnalyticsRouteImport } from './routes/options-analytics'
import { Route as OptionStrategyRouteImport } from './routes/option-strategy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketReplayRouteImport } from './routes/market-replay'
import { Route as MarketBreadthRouteImport } from './routes/market-breadth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveTerminalRouteImport } from './routes/live-terminal'
import { Route as LiveMarketTerminalRouteImport } from './routes/live-market-terminal'
import { Route as LiveLevelsRouteImport } from './routes/live-levels'
import { Route as GannGapOutlookRouteImport } from './routes/gann-gap-outlook'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as CombinedPcrRouteImport } from './routes/combined-pcr'
import { Route as BrokerRouteImport } from './routes/broker'
import { Route as BacktestingLabRouteImport } from './routes/backtesting-lab'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AstroRouteImport } from './routes/astro'
import { Route as AiDecisionCenterRouteImport } from './routes/ai-decision-center'
import { Route as AbsoluteIntradayValidationRouteImport } from './routes/absolute-intraday-validation'
import { Route as AbsoluteIntradayRouteImport } from './routes/absolute-intraday'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevDiagnosticsRouteImport } from './routes/dev.diagnostics'
import { Route as DevAstroFixtureCaptureRouteImport } from './routes/dev.astro-fixture-capture'
import { Route as DevAstroAuditRouteImport } from './routes/dev.astro-audit'
import { Route as CryptoPairRouteImport } from './routes/crypto.$pair'
import { Route as AuthenticatedTelegramLogRouteImport } from './routes/_authenticated/telegram-log'
import { Route as AuthenticatedStrategyAnalyticsRouteImport } from './routes/_authenticated/strategy-analytics'
import { Route as AuthenticatedSignalHistoryRouteImport } from './routes/_authenticated/signal-history'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResearchLabRouteImport } from './routes/_authenticated/research-lab'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentStatusRouteImport } from './routes/_authenticated/payment-status'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMultiAssetIntelligenceRouteImport } from './routes/_authenticated/multi-asset-intelligence'
import { Route as AuthenticatedLiveOptionTerminalRouteImport } from './routes/_authenticated/live-option-terminal'
import { Route as AuthenticatedLicenseRouteImport } from './routes/_authenticated/license'
import { Route as AuthenticatedInstitutionalIntelligenceRouteImport } from './routes/_authenticated/institutional-intelligence'
import { Route as AuthenticatedInstitutionalFlowRouteImport } from './routes/_authenticated/institutional-flow'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBacktestLabRouteImport } from './routes/_authenticated/backtest-lab'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAiMarketAssistantRouteImport } from './routes/_authenticated/ai-market-assistant'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedResearchLabSignalsRouteImport } from './routes/_authenticated/research-lab.signals'
import { Route as AuthenticatedResearchLabRunsRouteImport } from './routes/_authenticated/research-lab.runs'
import { Route as AuthenticatedResearchLabInstitutionalFlowRouteImport } from './routes/_authenticated/research-lab.institutional-flow'
import { Route as AuthenticatedResearchLabGannGapRouteImport } from './routes/_authenticated/research-lab.gann-gap'
import { Route as AuthenticatedResearchLabAlertsRouteImport } from './routes/_authenticated/research-lab.alerts'
import { Route as AuthenticatedAdminWidgetsRouteImport } from './routes/_authenticated/admin.widgets'
import { Route as AuthenticatedAdminTradingviewRouteImport } from './routes/_authenticated/admin.tradingview'
import { Route as AuthenticatedAdminSystemStatusRouteImport } from './routes/_authenticated/admin.system-status'
import { Route as AuthenticatedAdminStagingValidationRouteImport } from './routes/_authenticated/admin.staging-validation'
import { Route as AuthenticatedAdminResearchLabRouteImport } from './routes/_authenticated/admin.research-lab'
import { Route as AuthenticatedAdminReferralsRouteImport } from './routes/_authenticated/admin.referrals'
import { Route as AuthenticatedAdminReadinessRouteImport } from './routes/_authenticated/admin.readiness'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminLaunchReadinessRouteImport } from './routes/_authenticated/admin.launch-readiness'
import { Route as AuthenticatedAdminInstitutionalFlowRouteImport } from './routes/_authenticated/admin.institutional-flow'
import { Route as AuthenticatedAdminGannGapRouteImport } from './routes/_authenticated/admin.gann-gap'
import { Route as AuthenticatedAdminCoindcxRouteImport } from './routes/_authenticated/admin.coindcx'
import { Route as AuthenticatedAdminBetaReadinessRouteImport } from './routes/_authenticated/admin.beta-readiness'
import { Route as AuthenticatedAdminAlertsRouteImport } from './routes/_authenticated/admin.alerts'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'
import { Route as ApiPublicHooksMorningBriefRouteImport } from './routes/api/public/hooks/morning-brief'
import { Route as AuthenticatedResearchLabRunsRunIdRouteImport } from './routes/_authenticated/research-lab.runs.$runId'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyBuilderRoute = StrategyBuilderRouteImport.update({
  id: '/strategy-builder',
  path: '/strategy-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalAccuracyRoute = SignalAccuracyRouteImport.update({
  id: '/signal-accuracy',
  path: '/signal-accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesRoute = ReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsChainRoute = OptionsChainRouteImport.update({
  id: '/options-chain',
  path: '/options-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsAnalyticsRoute = OptionsAnalyticsRouteImport.update({
  id: '/options-analytics',
  path: '/options-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionStrategyRoute = OptionStrategyRouteImport.update({
  id: '/option-strategy',
  path: '/option-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketReplayRoute = MarketReplayRouteImport.update({
  id: '/market-replay',
  path: '/market-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketBreadthRoute = MarketBreadthRouteImport.update({
  id: '/market-breadth',
  path: '/market-breadth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTerminalRoute = LiveTerminalRouteImport.update({
  id: '/live-terminal',
  path: '/live-terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMarketTerminalRoute = LiveMarketTerminalRouteImport.update({
  id: '/live-market-terminal',
  path: '/live-market-terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLevelsRoute = LiveLevelsRouteImport.update({
  id: '/live-levels',
  path: '/live-levels',
  getParentRoute: () => rootRouteImport,
} as any)
const GannGapOutlookRoute = GannGapOutlookRouteImport.update({
  id: '/gann-gap-outlook',
  path: '/gann-gap-outlook',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinedPcrRoute = CombinedPcrRouteImport.update({
  id: '/combined-pcr',
  path: '/combined-pcr',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerRoute = BrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestingLabRoute = BacktestingLabRouteImport.update({
  id: '/backtesting-lab',
  path: '/backtesting-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroRoute = AstroRouteImport.update({
  id: '/astro',
  path: '/astro',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDecisionCenterRoute = AiDecisionCenterRouteImport.update({
  id: '/ai-decision-center',
  path: '/ai-decision-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsoluteIntradayValidationRoute =
  AbsoluteIntradayValidationRouteImport.update({
    id: '/absolute-intraday-validation',
    path: '/absolute-intraday-validation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AbsoluteIntradayRoute = AbsoluteIntradayRouteImport.update({
  id: '/absolute-intraday',
  path: '/absolute-intraday',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiagnosticsRoute = DevDiagnosticsRouteImport.update({
  id: '/dev/diagnostics',
  path: '/dev/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAstroFixtureCaptureRoute = DevAstroFixtureCaptureRouteImport.update({
  id: '/dev/astro-fixture-capture',
  path: '/dev/astro-fixture-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAstroAuditRoute = DevAstroAuditRouteImport.update({
  id: '/dev/astro-audit',
  path: '/dev/astro-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoPairRoute = CryptoPairRouteImport.update({
  id: '/$pair',
  path: '/$pair',
  getParentRoute: () => CryptoRoute,
} as any)
const AuthenticatedTelegramLogRoute =
  AuthenticatedTelegramLogRouteImport.update({
    id: '/telegram-log',
    path: '/telegram-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyAnalyticsRoute =
  AuthenticatedStrategyAnalyticsRouteImport.update({
    id: '/strategy-analytics',
    path: '/strategy-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSignalHistoryRoute =
  AuthenticatedSignalHistoryRouteImport.update({
    id: '/signal-history',
    path: '/signal-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchLabRoute =
  AuthenticatedResearchLabRouteImport.update({
    id: '/research-lab',
    path: '/research-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentStatusRoute =
  AuthenticatedPaymentStatusRouteImport.update({
    id: '/payment-status',
    path: '/payment-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMultiAssetIntelligenceRoute =
  AuthenticatedMultiAssetIntelligenceRouteImport.update({
    id: '/multi-asset-intelligence',
    path: '/multi-asset-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveOptionTerminalRoute =
  AuthenticatedLiveOptionTerminalRouteImport.update({
    id: '/live-option-terminal',
    path: '/live-option-terminal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLicenseRoute = AuthenticatedLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstitutionalIntelligenceRoute =
  AuthenticatedInstitutionalIntelligenceRouteImport.update({
    id: '/institutional-intelligence',
    path: '/institutional-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionalFlowRoute =
  AuthenticatedInstitutionalFlowRouteImport.update({
    id: '/institutional-flow',
    path: '/institutional-flow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacktestLabRoute =
  AuthenticatedBacktestLabRouteImport.update({
    id: '/backtest-lab',
    path: '/backtest-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiMarketAssistantRoute =
  AuthenticatedAiMarketAssistantRouteImport.update({
    id: '/ai-market-assistant',
    path: '/ai-market-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResearchLabSignalsRoute =
  AuthenticatedResearchLabSignalsRouteImport.update({
    id: '/signals',
    path: '/signals',
    getParentRoute: () => AuthenticatedResearchLabRoute,
  } as any)
const AuthenticatedResearchLabRunsRoute =
  AuthenticatedResearchLabRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedResearchLabRoute,
  } as any)
const AuthenticatedResearchLabInstitutionalFlowRoute =
  AuthenticatedResearchLabInstitutionalFlowRouteImport.update({
    id: '/institutional-flow',
    path: '/institutional-flow',
    getParentRoute: () => AuthenticatedResearchLabRoute,
  } as any)
const AuthenticatedResearchLabGannGapRoute =
  AuthenticatedResearchLabGannGapRouteImport.update({
    id: '/gann-gap',
    path: '/gann-gap',
    getParentRoute: () => AuthenticatedResearchLabRoute,
  } as any)
const AuthenticatedResearchLabAlertsRoute =
  AuthenticatedResearchLabAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedResearchLabRoute,
  } as any)
const AuthenticatedAdminWidgetsRoute =
  AuthenticatedAdminWidgetsRouteImport.update({
    id: '/admin/widgets',
    path: '/admin/widgets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTradingviewRoute =
  AuthenticatedAdminTradingviewRouteImport.update({
    id: '/admin/tradingview',
    path: '/admin/tradingview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSystemStatusRoute =
  AuthenticatedAdminSystemStatusRouteImport.update({
    id: '/admin/system-status',
    path: '/admin/system-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStagingValidationRoute =
  AuthenticatedAdminStagingValidationRouteImport.update({
    id: '/admin/staging-validation',
    path: '/admin/staging-validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminResearchLabRoute =
  AuthenticatedAdminResearchLabRouteImport.update({
    id: '/admin/research-lab',
    path: '/admin/research-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReferralsRoute =
  AuthenticatedAdminReferralsRouteImport.update({
    id: '/admin/referrals',
    path: '/admin/referrals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReadinessRoute =
  AuthenticatedAdminReadinessRouteImport.update({
    id: '/admin/readiness',
    path: '/admin/readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/admin/providers',
    path: '/admin/providers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLaunchReadinessRoute =
  AuthenticatedAdminLaunchReadinessRouteImport.update({
    id: '/admin/launch-readiness',
    path: '/admin/launch-readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInstitutionalFlowRoute =
  AuthenticatedAdminInstitutionalFlowRouteImport.update({
    id: '/admin/institutional-flow',
    path: '/admin/institutional-flow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGannGapRoute =
  AuthenticatedAdminGannGapRouteImport.update({
    id: '/admin/gann-gap',
    path: '/admin/gann-gap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoindcxRoute =
  AuthenticatedAdminCoindcxRouteImport.update({
    id: '/admin/coindcx',
    path: '/admin/coindcx',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBetaReadinessRoute =
  AuthenticatedAdminBetaReadinessRouteImport.update({
    id: '/admin/beta-readiness',
    path: '/admin/beta-readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAlertsRoute =
  AuthenticatedAdminAlertsRouteImport.update({
    id: '/admin/alerts',
    path: '/admin/alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMorningBriefRoute =
  ApiPublicHooksMorningBriefRouteImport.update({
    id: '/api/public/hooks/morning-brief',
    path: '/api/public/hooks/morning-brief',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResearchLabRunsRunIdRoute =
  AuthenticatedResearchLabRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AuthenticatedResearchLabRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absolute-intraday': typeof AbsoluteIntradayRoute
  '/absolute-intraday-validation': typeof AbsoluteIntradayValidationRoute
  '/ai-decision-center': typeof AiDecisionCenterRoute
  '/astro': typeof AstroRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/backtesting-lab': typeof BacktestingLabRoute
  '/broker': typeof BrokerRoute
  '/combined-pcr': typeof CombinedPcrRoute
  '/crypto': typeof CryptoRouteWithChildren
  '/decision': typeof DecisionRoute
  '/gann-gap-outlook': typeof GannGapOutlookRoute
  '/live-levels': typeof LiveLevelsRoute
  '/live-market-terminal': typeof LiveMarketTerminalRoute
  '/live-terminal': typeof LiveTerminalRoute
  '/login': typeof LoginRoute
  '/market-breadth': typeof MarketBreadthRoute
  '/market-replay': typeof MarketReplayRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/option-strategy': typeof OptionStrategyRoute
  '/options-analytics': typeof OptionsAnalyticsRoute
  '/options-chain': typeof OptionsChainRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/risk': typeof RiskRoute
  '/signal-accuracy': typeof SignalAccuracyRoute
  '/status': typeof StatusRoute
  '/strategy-builder': typeof StrategyBuilderRoute
  '/terms': typeof TermsRoute
  '/watchlist': typeof WatchlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-market-assistant': typeof AuthenticatedAiMarketAssistantRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/backtest-lab': typeof AuthenticatedBacktestLabRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/institutional-flow': typeof AuthenticatedInstitutionalFlowRoute
  '/institutional-intelligence': typeof AuthenticatedInstitutionalIntelligenceRoute
  '/license': typeof AuthenticatedLicenseRoute
  '/live-option-terminal': typeof AuthenticatedLiveOptionTerminalRoute
  '/multi-asset-intelligence': typeof AuthenticatedMultiAssetIntelligenceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-status': typeof AuthenticatedPaymentStatusRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/research-lab': typeof AuthenticatedResearchLabRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/signal-history': typeof AuthenticatedSignalHistoryRoute
  '/strategy-analytics': typeof AuthenticatedStrategyAnalyticsRoute
  '/telegram-log': typeof AuthenticatedTelegramLogRoute
  '/crypto/$pair': typeof CryptoPairRoute
  '/dev/astro-audit': typeof DevAstroAuditRoute
  '/dev/astro-fixture-capture': typeof DevAstroFixtureCaptureRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/beta-readiness': typeof AuthenticatedAdminBetaReadinessRoute
  '/admin/coindcx': typeof AuthenticatedAdminCoindcxRoute
  '/admin/gann-gap': typeof AuthenticatedAdminGannGapRoute
  '/admin/institutional-flow': typeof AuthenticatedAdminInstitutionalFlowRoute
  '/admin/launch-readiness': typeof AuthenticatedAdminLaunchReadinessRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/readiness': typeof AuthenticatedAdminReadinessRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/research-lab': typeof AuthenticatedAdminResearchLabRoute
  '/admin/staging-validation': typeof AuthenticatedAdminStagingValidationRoute
  '/admin/system-status': typeof AuthenticatedAdminSystemStatusRoute
  '/admin/tradingview': typeof AuthenticatedAdminTradingviewRoute
  '/admin/widgets': typeof AuthenticatedAdminWidgetsRoute
  '/research-lab/alerts': typeof AuthenticatedResearchLabAlertsRoute
  '/research-lab/gann-gap': typeof AuthenticatedResearchLabGannGapRoute
  '/research-lab/institutional-flow': typeof AuthenticatedResearchLabInstitutionalFlowRoute
  '/research-lab/runs': typeof AuthenticatedResearchLabRunsRouteWithChildren
  '/research-lab/signals': typeof AuthenticatedResearchLabSignalsRoute
  '/research-lab/runs/$runId': typeof AuthenticatedResearchLabRunsRunIdRoute
  '/api/public/hooks/morning-brief': typeof ApiPublicHooksMorningBriefRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absolute-intraday': typeof AbsoluteIntradayRoute
  '/absolute-intraday-validation': typeof AbsoluteIntradayValidationRoute
  '/ai-decision-center': typeof AiDecisionCenterRoute
  '/astro': typeof AstroRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/backtesting-lab': typeof BacktestingLabRoute
  '/broker': typeof BrokerRoute
  '/combined-pcr': typeof CombinedPcrRoute
  '/crypto': typeof CryptoRouteWithChildren
  '/decision': typeof DecisionRoute
  '/gann-gap-outlook': typeof GannGapOutlookRoute
  '/live-levels': typeof LiveLevelsRoute
  '/live-market-terminal': typeof LiveMarketTerminalRoute
  '/live-terminal': typeof LiveTerminalRoute
  '/login': typeof LoginRoute
  '/market-breadth': typeof MarketBreadthRoute
  '/market-replay': typeof MarketReplayRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/option-strategy': typeof OptionStrategyRoute
  '/options-analytics': typeof OptionsAnalyticsRoute
  '/options-chain': typeof OptionsChainRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/risk': typeof RiskRoute
  '/signal-accuracy': typeof SignalAccuracyRoute
  '/status': typeof StatusRoute
  '/strategy-builder': typeof StrategyBuilderRoute
  '/terms': typeof TermsRoute
  '/watchlist': typeof WatchlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-market-assistant': typeof AuthenticatedAiMarketAssistantRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/backtest-lab': typeof AuthenticatedBacktestLabRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/institutional-flow': typeof AuthenticatedInstitutionalFlowRoute
  '/institutional-intelligence': typeof AuthenticatedInstitutionalIntelligenceRoute
  '/license': typeof AuthenticatedLicenseRoute
  '/live-option-terminal': typeof AuthenticatedLiveOptionTerminalRoute
  '/multi-asset-intelligence': typeof AuthenticatedMultiAssetIntelligenceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-status': typeof AuthenticatedPaymentStatusRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/research-lab': typeof AuthenticatedResearchLabRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/signal-history': typeof AuthenticatedSignalHistoryRoute
  '/strategy-analytics': typeof AuthenticatedStrategyAnalyticsRoute
  '/telegram-log': typeof AuthenticatedTelegramLogRoute
  '/crypto/$pair': typeof CryptoPairRoute
  '/dev/astro-audit': typeof DevAstroAuditRoute
  '/dev/astro-fixture-capture': typeof DevAstroFixtureCaptureRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/beta-readiness': typeof AuthenticatedAdminBetaReadinessRoute
  '/admin/coindcx': typeof AuthenticatedAdminCoindcxRoute
  '/admin/gann-gap': typeof AuthenticatedAdminGannGapRoute
  '/admin/institutional-flow': typeof AuthenticatedAdminInstitutionalFlowRoute
  '/admin/launch-readiness': typeof AuthenticatedAdminLaunchReadinessRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/readiness': typeof AuthenticatedAdminReadinessRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/research-lab': typeof AuthenticatedAdminResearchLabRoute
  '/admin/staging-validation': typeof AuthenticatedAdminStagingValidationRoute
  '/admin/system-status': typeof AuthenticatedAdminSystemStatusRoute
  '/admin/tradingview': typeof AuthenticatedAdminTradingviewRoute
  '/admin/widgets': typeof AuthenticatedAdminWidgetsRoute
  '/research-lab/alerts': typeof AuthenticatedResearchLabAlertsRoute
  '/research-lab/gann-gap': typeof AuthenticatedResearchLabGannGapRoute
  '/research-lab/institutional-flow': typeof AuthenticatedResearchLabInstitutionalFlowRoute
  '/research-lab/runs': typeof AuthenticatedResearchLabRunsRouteWithChildren
  '/research-lab/signals': typeof AuthenticatedResearchLabSignalsRoute
  '/research-lab/runs/$runId': typeof AuthenticatedResearchLabRunsRunIdRoute
  '/api/public/hooks/morning-brief': typeof ApiPublicHooksMorningBriefRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/absolute-intraday': typeof AbsoluteIntradayRoute
  '/absolute-intraday-validation': typeof AbsoluteIntradayValidationRoute
  '/ai-decision-center': typeof AiDecisionCenterRoute
  '/astro': typeof AstroRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/backtesting-lab': typeof BacktestingLabRoute
  '/broker': typeof BrokerRoute
  '/combined-pcr': typeof CombinedPcrRoute
  '/crypto': typeof CryptoRouteWithChildren
  '/decision': typeof DecisionRoute
  '/gann-gap-outlook': typeof GannGapOutlookRoute
  '/live-levels': typeof LiveLevelsRoute
  '/live-market-terminal': typeof LiveMarketTerminalRoute
  '/live-terminal': typeof LiveTerminalRoute
  '/login': typeof LoginRoute
  '/market-breadth': typeof MarketBreadthRoute
  '/market-replay': typeof MarketReplayRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/option-strategy': typeof OptionStrategyRoute
  '/options-analytics': typeof OptionsAnalyticsRoute
  '/options-chain': typeof OptionsChainRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/risk': typeof RiskRoute
  '/signal-accuracy': typeof SignalAccuracyRoute
  '/status': typeof StatusRoute
  '/strategy-builder': typeof StrategyBuilderRoute
  '/terms': typeof TermsRoute
  '/watchlist': typeof WatchlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/ai-market-assistant': typeof AuthenticatedAiMarketAssistantRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/backtest-lab': typeof AuthenticatedBacktestLabRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/institutional-flow': typeof AuthenticatedInstitutionalFlowRoute
  '/_authenticated/institutional-intelligence': typeof AuthenticatedInstitutionalIntelligenceRoute
  '/_authenticated/license': typeof AuthenticatedLicenseRoute
  '/_authenticated/live-option-terminal': typeof AuthenticatedLiveOptionTerminalRoute
  '/_authenticated/multi-asset-intelligence': typeof AuthenticatedMultiAssetIntelligenceRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payment-status': typeof AuthenticatedPaymentStatusRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/research-lab': typeof AuthenticatedResearchLabRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/signal-history': typeof AuthenticatedSignalHistoryRoute
  '/_authenticated/strategy-analytics': typeof AuthenticatedStrategyAnalyticsRoute
  '/_authenticated/telegram-log': typeof AuthenticatedTelegramLogRoute
  '/crypto/$pair': typeof CryptoPairRoute
  '/dev/astro-audit': typeof DevAstroAuditRoute
  '/dev/astro-fixture-capture': typeof DevAstroFixtureCaptureRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/_authenticated/admin/beta-readiness': typeof AuthenticatedAdminBetaReadinessRoute
  '/_authenticated/admin/coindcx': typeof AuthenticatedAdminCoindcxRoute
  '/_authenticated/admin/gann-gap': typeof AuthenticatedAdminGannGapRoute
  '/_authenticated/admin/institutional-flow': typeof AuthenticatedAdminInstitutionalFlowRoute
  '/_authenticated/admin/launch-readiness': typeof AuthenticatedAdminLaunchReadinessRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/admin/readiness': typeof AuthenticatedAdminReadinessRoute
  '/_authenticated/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/_authenticated/admin/research-lab': typeof AuthenticatedAdminResearchLabRoute
  '/_authenticated/admin/staging-validation': typeof AuthenticatedAdminStagingValidationRoute
  '/_authenticated/admin/system-status': typeof AuthenticatedAdminSystemStatusRoute
  '/_authenticated/admin/tradingview': typeof AuthenticatedAdminTradingviewRoute
  '/_authenticated/admin/widgets': typeof AuthenticatedAdminWidgetsRoute
  '/_authenticated/research-lab/alerts': typeof AuthenticatedResearchLabAlertsRoute
  '/_authenticated/research-lab/gann-gap': typeof AuthenticatedResearchLabGannGapRoute
  '/_authenticated/research-lab/institutional-flow': typeof AuthenticatedResearchLabInstitutionalFlowRoute
  '/_authenticated/research-lab/runs': typeof AuthenticatedResearchLabRunsRouteWithChildren
  '/_authenticated/research-lab/signals': typeof AuthenticatedResearchLabSignalsRoute
  '/_authenticated/research-lab/runs/$runId': typeof AuthenticatedResearchLabRunsRunIdRoute
  '/api/public/hooks/morning-brief': typeof ApiPublicHooksMorningBriefRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/absolute-intraday'
    | '/absolute-intraday-validation'
    | '/ai-decision-center'
    | '/astro'
    | '/auth'
    | '/backtest'
    | '/backtesting-lab'
    | '/broker'
    | '/combined-pcr'
    | '/crypto'
    | '/decision'
    | '/gann-gap-outlook'
    | '/live-levels'
    | '/live-market-terminal'
    | '/live-terminal'
    | '/login'
    | '/market-breadth'
    | '/market-replay'
    | '/mcp'
    | '/news'
    | '/option-strategy'
    | '/options-analytics'
    | '/options-chain'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/release-notes'
    | '/risk'
    | '/signal-accuracy'
    | '/status'
    | '/strategy-builder'
    | '/terms'
    | '/watchlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-market-assistant'
    | '/alerts'
    | '/backtest-lab'
    | '/billing'
    | '/institutional-flow'
    | '/institutional-intelligence'
    | '/license'
    | '/live-option-terminal'
    | '/multi-asset-intelligence'
    | '/notifications'
    | '/payment-status'
    | '/profile'
    | '/referrals'
    | '/research-lab'
    | '/settings'
    | '/signal-history'
    | '/strategy-analytics'
    | '/telegram-log'
    | '/crypto/$pair'
    | '/dev/astro-audit'
    | '/dev/astro-fixture-capture'
    | '/dev/diagnostics'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/alerts'
    | '/admin/beta-readiness'
    | '/admin/coindcx'
    | '/admin/gann-gap'
    | '/admin/institutional-flow'
    | '/admin/launch-readiness'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/readiness'
    | '/admin/referrals'
    | '/admin/research-lab'
    | '/admin/staging-validation'
    | '/admin/system-status'
    | '/admin/tradingview'
    | '/admin/widgets'
    | '/research-lab/alerts'
    | '/research-lab/gann-gap'
    | '/research-lab/institutional-flow'
    | '/research-lab/runs'
    | '/research-lab/signals'
    | '/research-lab/runs/$runId'
    | '/api/public/hooks/morning-brief'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/absolute-intraday'
    | '/absolute-intraday-validation'
    | '/ai-decision-center'
    | '/astro'
    | '/auth'
    | '/backtest'
    | '/backtesting-lab'
    | '/broker'
    | '/combined-pcr'
    | '/crypto'
    | '/decision'
    | '/gann-gap-outlook'
    | '/live-levels'
    | '/live-market-terminal'
    | '/live-terminal'
    | '/login'
    | '/market-breadth'
    | '/market-replay'
    | '/mcp'
    | '/news'
    | '/option-strategy'
    | '/options-analytics'
    | '/options-chain'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/release-notes'
    | '/risk'
    | '/signal-accuracy'
    | '/status'
    | '/strategy-builder'
    | '/terms'
    | '/watchlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-market-assistant'
    | '/alerts'
    | '/backtest-lab'
    | '/billing'
    | '/institutional-flow'
    | '/institutional-intelligence'
    | '/license'
    | '/live-option-terminal'
    | '/multi-asset-intelligence'
    | '/notifications'
    | '/payment-status'
    | '/profile'
    | '/referrals'
    | '/research-lab'
    | '/settings'
    | '/signal-history'
    | '/strategy-analytics'
    | '/telegram-log'
    | '/crypto/$pair'
    | '/dev/astro-audit'
    | '/dev/astro-fixture-capture'
    | '/dev/diagnostics'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/alerts'
    | '/admin/beta-readiness'
    | '/admin/coindcx'
    | '/admin/gann-gap'
    | '/admin/institutional-flow'
    | '/admin/launch-readiness'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/readiness'
    | '/admin/referrals'
    | '/admin/research-lab'
    | '/admin/staging-validation'
    | '/admin/system-status'
    | '/admin/tradingview'
    | '/admin/widgets'
    | '/research-lab/alerts'
    | '/research-lab/gann-gap'
    | '/research-lab/institutional-flow'
    | '/research-lab/runs'
    | '/research-lab/signals'
    | '/research-lab/runs/$runId'
    | '/api/public/hooks/morning-brief'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/absolute-intraday'
    | '/absolute-intraday-validation'
    | '/ai-decision-center'
    | '/astro'
    | '/auth'
    | '/backtest'
    | '/backtesting-lab'
    | '/broker'
    | '/combined-pcr'
    | '/crypto'
    | '/decision'
    | '/gann-gap-outlook'
    | '/live-levels'
    | '/live-market-terminal'
    | '/live-terminal'
    | '/login'
    | '/market-breadth'
    | '/market-replay'
    | '/mcp'
    | '/news'
    | '/option-strategy'
    | '/options-analytics'
    | '/options-chain'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/release-notes'
    | '/risk'
    | '/signal-accuracy'
    | '/status'
    | '/strategy-builder'
    | '/terms'
    | '/watchlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/ai-market-assistant'
    | '/_authenticated/alerts'
    | '/_authenticated/backtest-lab'
    | '/_authenticated/billing'
    | '/_authenticated/institutional-flow'
    | '/_authenticated/institutional-intelligence'
    | '/_authenticated/license'
    | '/_authenticated/live-option-terminal'
    | '/_authenticated/multi-asset-intelligence'
    | '/_authenticated/notifications'
    | '/_authenticated/payment-status'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/research-lab'
    | '/_authenticated/settings'
    | '/_authenticated/signal-history'
    | '/_authenticated/strategy-analytics'
    | '/_authenticated/telegram-log'
    | '/crypto/$pair'
    | '/dev/astro-audit'
    | '/dev/astro-fixture-capture'
    | '/dev/diagnostics'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/alerts'
    | '/_authenticated/admin/beta-readiness'
    | '/_authenticated/admin/coindcx'
    | '/_authenticated/admin/gann-gap'
    | '/_authenticated/admin/institutional-flow'
    | '/_authenticated/admin/launch-readiness'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/readiness'
    | '/_authenticated/admin/referrals'
    | '/_authenticated/admin/research-lab'
    | '/_authenticated/admin/staging-validation'
    | '/_authenticated/admin/system-status'
    | '/_authenticated/admin/tradingview'
    | '/_authenticated/admin/widgets'
    | '/_authenticated/research-lab/alerts'
    | '/_authenticated/research-lab/gann-gap'
    | '/_authenticated/research-lab/institutional-flow'
    | '/_authenticated/research-lab/runs'
    | '/_authenticated/research-lab/signals'
    | '/_authenticated/research-lab/runs/$runId'
    | '/api/public/hooks/morning-brief'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AbsoluteIntradayRoute: typeof AbsoluteIntradayRoute
  AbsoluteIntradayValidationRoute: typeof AbsoluteIntradayValidationRoute
  AiDecisionCenterRoute: typeof AiDecisionCenterRoute
  AstroRoute: typeof AstroRoute
  AuthRoute: typeof AuthRoute
  BacktestRoute: typeof BacktestRoute
  BacktestingLabRoute: typeof BacktestingLabRoute
  BrokerRoute: typeof BrokerRoute
  CombinedPcrRoute: typeof CombinedPcrRoute
  CryptoRoute: typeof CryptoRouteWithChildren
  DecisionRoute: typeof DecisionRoute
  GannGapOutlookRoute: typeof GannGapOutlookRoute
  LiveLevelsRoute: typeof LiveLevelsRoute
  LiveMarketTerminalRoute: typeof LiveMarketTerminalRoute
  LiveTerminalRoute: typeof LiveTerminalRoute
  LoginRoute: typeof LoginRoute
  MarketBreadthRoute: typeof MarketBreadthRoute
  MarketReplayRoute: typeof MarketReplayRoute
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRoute
  OptionStrategyRoute: typeof OptionStrategyRoute
  OptionsAnalyticsRoute: typeof OptionsAnalyticsRoute
  OptionsChainRoute: typeof OptionsChainRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReleaseNotesRoute: typeof ReleaseNotesRoute
  RiskRoute: typeof RiskRoute
  SignalAccuracyRoute: typeof SignalAccuracyRoute
  StatusRoute: typeof StatusRoute
  StrategyBuilderRoute: typeof StrategyBuilderRoute
  TermsRoute: typeof TermsRoute
  WatchlistRoute: typeof WatchlistRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DevAstroAuditRoute: typeof DevAstroAuditRoute
  DevAstroFixtureCaptureRoute: typeof DevAstroFixtureCaptureRoute
  DevDiagnosticsRoute: typeof DevDiagnosticsRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksMorningBriefRoute: typeof ApiPublicHooksMorningBriefRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-builder': {
      id: '/strategy-builder'
      path: '/strategy-builder'
      fullPath: '/strategy-builder'
      preLoaderRoute: typeof StrategyBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-accuracy': {
      id: '/signal-accuracy'
      path: '/signal-accuracy'
      fullPath: '/signal-accuracy'
      preLoaderRoute: typeof SignalAccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes': {
      id: '/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof ReleaseNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options-chain': {
      id: '/options-chain'
      path: '/options-chain'
      fullPath: '/options-chain'
      preLoaderRoute: typeof OptionsChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options-analytics': {
      id: '/options-analytics'
      path: '/options-analytics'
      fullPath: '/options-analytics'
      preLoaderRoute: typeof OptionsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option-strategy': {
      id: '/option-strategy'
      path: '/option-strategy'
      fullPath: '/option-strategy'
      preLoaderRoute: typeof OptionStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-replay': {
      id: '/market-replay'
      path: '/market-replay'
      fullPath: '/market-replay'
      preLoaderRoute: typeof MarketReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-breadth': {
      id: '/market-breadth'
      path: '/market-breadth'
      fullPath: '/market-breadth'
      preLoaderRoute: typeof MarketBreadthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-terminal': {
      id: '/live-terminal'
      path: '/live-terminal'
      fullPath: '/live-terminal'
      preLoaderRoute: typeof LiveTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-market-terminal': {
      id: '/live-market-terminal'
      path: '/live-market-terminal'
      fullPath: '/live-market-terminal'
      preLoaderRoute: typeof LiveMarketTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-levels': {
      id: '/live-levels'
      path: '/live-levels'
      fullPath: '/live-levels'
      preLoaderRoute: typeof LiveLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gann-gap-outlook': {
      id: '/gann-gap-outlook'
      path: '/gann-gap-outlook'
      fullPath: '/gann-gap-outlook'
      preLoaderRoute: typeof GannGapOutlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combined-pcr': {
      id: '/combined-pcr'
      path: '/combined-pcr'
      fullPath: '/combined-pcr'
      preLoaderRoute: typeof CombinedPcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker': {
      id: '/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof BrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtesting-lab': {
      id: '/backtesting-lab'
      path: '/backtesting-lab'
      fullPath: '/backtesting-lab'
      preLoaderRoute: typeof BacktestingLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astro': {
      id: '/astro'
      path: '/astro'
      fullPath: '/astro'
      preLoaderRoute: typeof AstroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-decision-center': {
      id: '/ai-decision-center'
      path: '/ai-decision-center'
      fullPath: '/ai-decision-center'
      preLoaderRoute: typeof AiDecisionCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absolute-intraday-validation': {
      id: '/absolute-intraday-validation'
      path: '/absolute-intraday-validation'
      fullPath: '/absolute-intraday-validation'
      preLoaderRoute: typeof AbsoluteIntradayValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absolute-intraday': {
      id: '/absolute-intraday'
      path: '/absolute-intraday'
      fullPath: '/absolute-intraday'
      preLoaderRoute: typeof AbsoluteIntradayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/diagnostics': {
      id: '/dev/diagnostics'
      path: '/dev/diagnostics'
      fullPath: '/dev/diagnostics'
      preLoaderRoute: typeof DevDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/astro-fixture-capture': {
      id: '/dev/astro-fixture-capture'
      path: '/dev/astro-fixture-capture'
      fullPath: '/dev/astro-fixture-capture'
      preLoaderRoute: typeof DevAstroFixtureCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/astro-audit': {
      id: '/dev/astro-audit'
      path: '/dev/astro-audit'
      fullPath: '/dev/astro-audit'
      preLoaderRoute: typeof DevAstroAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto/$pair': {
      id: '/crypto/$pair'
      path: '/$pair'
      fullPath: '/crypto/$pair'
      preLoaderRoute: typeof CryptoPairRouteImport
      parentRoute: typeof CryptoRoute
    }
    '/_authenticated/telegram-log': {
      id: '/_authenticated/telegram-log'
      path: '/telegram-log'
      fullPath: '/telegram-log'
      preLoaderRoute: typeof AuthenticatedTelegramLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy-analytics': {
      id: '/_authenticated/strategy-analytics'
      path: '/strategy-analytics'
      fullPath: '/strategy-analytics'
      preLoaderRoute: typeof AuthenticatedStrategyAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signal-history': {
      id: '/_authenticated/signal-history'
      path: '/signal-history'
      fullPath: '/signal-history'
      preLoaderRoute: typeof AuthenticatedSignalHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research-lab': {
      id: '/_authenticated/research-lab'
      path: '/research-lab'
      fullPath: '/research-lab'
      preLoaderRoute: typeof AuthenticatedResearchLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-status': {
      id: '/_authenticated/payment-status'
      path: '/payment-status'
      fullPath: '/payment-status'
      preLoaderRoute: typeof AuthenticatedPaymentStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/multi-asset-intelligence': {
      id: '/_authenticated/multi-asset-intelligence'
      path: '/multi-asset-intelligence'
      fullPath: '/multi-asset-intelligence'
      preLoaderRoute: typeof AuthenticatedMultiAssetIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-option-terminal': {
      id: '/_authenticated/live-option-terminal'
      path: '/live-option-terminal'
      fullPath: '/live-option-terminal'
      preLoaderRoute: typeof AuthenticatedLiveOptionTerminalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/license': {
      id: '/_authenticated/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof AuthenticatedLicenseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institutional-intelligence': {
      id: '/_authenticated/institutional-intelligence'
      path: '/institutional-intelligence'
      fullPath: '/institutional-intelligence'
      preLoaderRoute: typeof AuthenticatedInstitutionalIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institutional-flow': {
      id: '/_authenticated/institutional-flow'
      path: '/institutional-flow'
      fullPath: '/institutional-flow'
      preLoaderRoute: typeof AuthenticatedInstitutionalFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtest-lab': {
      id: '/_authenticated/backtest-lab'
      path: '/backtest-lab'
      fullPath: '/backtest-lab'
      preLoaderRoute: typeof AuthenticatedBacktestLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-market-assistant': {
      id: '/_authenticated/ai-market-assistant'
      path: '/ai-market-assistant'
      fullPath: '/ai-market-assistant'
      preLoaderRoute: typeof AuthenticatedAiMarketAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/research-lab/signals': {
      id: '/_authenticated/research-lab/signals'
      path: '/signals'
      fullPath: '/research-lab/signals'
      preLoaderRoute: typeof AuthenticatedResearchLabSignalsRouteImport
      parentRoute: typeof AuthenticatedResearchLabRoute
    }
    '/_authenticated/research-lab/runs': {
      id: '/_authenticated/research-lab/runs'
      path: '/runs'
      fullPath: '/research-lab/runs'
      preLoaderRoute: typeof AuthenticatedResearchLabRunsRouteImport
      parentRoute: typeof AuthenticatedResearchLabRoute
    }
    '/_authenticated/research-lab/institutional-flow': {
      id: '/_authenticated/research-lab/institutional-flow'
      path: '/institutional-flow'
      fullPath: '/research-lab/institutional-flow'
      preLoaderRoute: typeof AuthenticatedResearchLabInstitutionalFlowRouteImport
      parentRoute: typeof AuthenticatedResearchLabRoute
    }
    '/_authenticated/research-lab/gann-gap': {
      id: '/_authenticated/research-lab/gann-gap'
      path: '/gann-gap'
      fullPath: '/research-lab/gann-gap'
      preLoaderRoute: typeof AuthenticatedResearchLabGannGapRouteImport
      parentRoute: typeof AuthenticatedResearchLabRoute
    }
    '/_authenticated/research-lab/alerts': {
      id: '/_authenticated/research-lab/alerts'
      path: '/alerts'
      fullPath: '/research-lab/alerts'
      preLoaderRoute: typeof AuthenticatedResearchLabAlertsRouteImport
      parentRoute: typeof AuthenticatedResearchLabRoute
    }
    '/_authenticated/admin/widgets': {
      id: '/_authenticated/admin/widgets'
      path: '/admin/widgets'
      fullPath: '/admin/widgets'
      preLoaderRoute: typeof AuthenticatedAdminWidgetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tradingview': {
      id: '/_authenticated/admin/tradingview'
      path: '/admin/tradingview'
      fullPath: '/admin/tradingview'
      preLoaderRoute: typeof AuthenticatedAdminTradingviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/system-status': {
      id: '/_authenticated/admin/system-status'
      path: '/admin/system-status'
      fullPath: '/admin/system-status'
      preLoaderRoute: typeof AuthenticatedAdminSystemStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/staging-validation': {
      id: '/_authenticated/admin/staging-validation'
      path: '/admin/staging-validation'
      fullPath: '/admin/staging-validation'
      preLoaderRoute: typeof AuthenticatedAdminStagingValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/research-lab': {
      id: '/_authenticated/admin/research-lab'
      path: '/admin/research-lab'
      fullPath: '/admin/research-lab'
      preLoaderRoute: typeof AuthenticatedAdminResearchLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/referrals': {
      id: '/_authenticated/admin/referrals'
      path: '/admin/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/readiness': {
      id: '/_authenticated/admin/readiness'
      path: '/admin/readiness'
      fullPath: '/admin/readiness'
      preLoaderRoute: typeof AuthenticatedAdminReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/launch-readiness': {
      id: '/_authenticated/admin/launch-readiness'
      path: '/admin/launch-readiness'
      fullPath: '/admin/launch-readiness'
      preLoaderRoute: typeof AuthenticatedAdminLaunchReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/institutional-flow': {
      id: '/_authenticated/admin/institutional-flow'
      path: '/admin/institutional-flow'
      fullPath: '/admin/institutional-flow'
      preLoaderRoute: typeof AuthenticatedAdminInstitutionalFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gann-gap': {
      id: '/_authenticated/admin/gann-gap'
      path: '/admin/gann-gap'
      fullPath: '/admin/gann-gap'
      preLoaderRoute: typeof AuthenticatedAdminGannGapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/coindcx': {
      id: '/_authenticated/admin/coindcx'
      path: '/admin/coindcx'
      fullPath: '/admin/coindcx'
      preLoaderRoute: typeof AuthenticatedAdminCoindcxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/beta-readiness': {
      id: '/_authenticated/admin/beta-readiness'
      path: '/admin/beta-readiness'
      fullPath: '/admin/beta-readiness'
      preLoaderRoute: typeof AuthenticatedAdminBetaReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/alerts': {
      id: '/_authenticated/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AuthenticatedAdminAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/morning-brief': {
      id: '/api/public/hooks/morning-brief'
      path: '/api/public/hooks/morning-brief'
      fullPath: '/api/public/hooks/morning-brief'
      preLoaderRoute: typeof ApiPublicHooksMorningBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/research-lab/runs/$runId': {
      id: '/_authenticated/research-lab/runs/$runId'
      path: '/$runId'
      fullPath: '/research-lab/runs/$runId'
      preLoaderRoute: typeof AuthenticatedResearchLabRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedResearchLabRunsRoute
    }
  }
}

interface AuthenticatedResearchLabRunsRouteChildren {
  AuthenticatedResearchLabRunsRunIdRoute: typeof AuthenticatedResearchLabRunsRunIdRoute
}

const AuthenticatedResearchLabRunsRouteChildren: AuthenticatedResearchLabRunsRouteChildren =
  {
    AuthenticatedResearchLabRunsRunIdRoute:
      AuthenticatedResearchLabRunsRunIdRoute,
  }

const AuthenticatedResearchLabRunsRouteWithChildren =
  AuthenticatedResearchLabRunsRoute._addFileChildren(
    AuthenticatedResearchLabRunsRouteChildren,
  )

interface AuthenticatedResearchLabRouteChildren {
  AuthenticatedResearchLabAlertsRoute: typeof AuthenticatedResearchLabAlertsRoute
  AuthenticatedResearchLabGannGapRoute: typeof AuthenticatedResearchLabGannGapRoute
  AuthenticatedResearchLabInstitutionalFlowRoute: typeof AuthenticatedResearchLabInstitutionalFlowRoute
  AuthenticatedResearchLabRunsRoute: typeof AuthenticatedResearchLabRunsRouteWithChildren
  AuthenticatedResearchLabSignalsRoute: typeof AuthenticatedResearchLabSignalsRoute
}

const AuthenticatedResearchLabRouteChildren: AuthenticatedResearchLabRouteChildren =
  {
    AuthenticatedResearchLabAlertsRoute: AuthenticatedResearchLabAlertsRoute,
    AuthenticatedResearchLabGannGapRoute: AuthenticatedResearchLabGannGapRoute,
    AuthenticatedResearchLabInstitutionalFlowRoute:
      AuthenticatedResearchLabInstitutionalFlowRoute,
    AuthenticatedResearchLabRunsRoute:
      AuthenticatedResearchLabRunsRouteWithChildren,
    AuthenticatedResearchLabSignalsRoute: AuthenticatedResearchLabSignalsRoute,
  }

const AuthenticatedResearchLabRouteWithChildren =
  AuthenticatedResearchLabRoute._addFileChildren(
    AuthenticatedResearchLabRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiMarketAssistantRoute: typeof AuthenticatedAiMarketAssistantRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBacktestLabRoute: typeof AuthenticatedBacktestLabRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedInstitutionalFlowRoute: typeof AuthenticatedInstitutionalFlowRoute
  AuthenticatedInstitutionalIntelligenceRoute: typeof AuthenticatedInstitutionalIntelligenceRoute
  AuthenticatedLicenseRoute: typeof AuthenticatedLicenseRoute
  AuthenticatedLiveOptionTerminalRoute: typeof AuthenticatedLiveOptionTerminalRoute
  AuthenticatedMultiAssetIntelligenceRoute: typeof AuthenticatedMultiAssetIntelligenceRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentStatusRoute: typeof AuthenticatedPaymentStatusRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedResearchLabRoute: typeof AuthenticatedResearchLabRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSignalHistoryRoute: typeof AuthenticatedSignalHistoryRoute
  AuthenticatedStrategyAnalyticsRoute: typeof AuthenticatedStrategyAnalyticsRoute
  AuthenticatedTelegramLogRoute: typeof AuthenticatedTelegramLogRoute
  AuthenticatedAdminAlertsRoute: typeof AuthenticatedAdminAlertsRoute
  AuthenticatedAdminBetaReadinessRoute: typeof AuthenticatedAdminBetaReadinessRoute
  AuthenticatedAdminCoindcxRoute: typeof AuthenticatedAdminCoindcxRoute
  AuthenticatedAdminGannGapRoute: typeof AuthenticatedAdminGannGapRoute
  AuthenticatedAdminInstitutionalFlowRoute: typeof AuthenticatedAdminInstitutionalFlowRoute
  AuthenticatedAdminLaunchReadinessRoute: typeof AuthenticatedAdminLaunchReadinessRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminReadinessRoute: typeof AuthenticatedAdminReadinessRoute
  AuthenticatedAdminReferralsRoute: typeof AuthenticatedAdminReferralsRoute
  AuthenticatedAdminResearchLabRoute: typeof AuthenticatedAdminResearchLabRoute
  AuthenticatedAdminStagingValidationRoute: typeof AuthenticatedAdminStagingValidationRoute
  AuthenticatedAdminSystemStatusRoute: typeof AuthenticatedAdminSystemStatusRoute
  AuthenticatedAdminTradingviewRoute: typeof AuthenticatedAdminTradingviewRoute
  AuthenticatedAdminWidgetsRoute: typeof AuthenticatedAdminWidgetsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiMarketAssistantRoute: AuthenticatedAiMarketAssistantRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBacktestLabRoute: AuthenticatedBacktestLabRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedInstitutionalFlowRoute: AuthenticatedInstitutionalFlowRoute,
  AuthenticatedInstitutionalIntelligenceRoute:
    AuthenticatedInstitutionalIntelligenceRoute,
  AuthenticatedLicenseRoute: AuthenticatedLicenseRoute,
  AuthenticatedLiveOptionTerminalRoute: AuthenticatedLiveOptionTerminalRoute,
  AuthenticatedMultiAssetIntelligenceRoute:
    AuthenticatedMultiAssetIntelligenceRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentStatusRoute: AuthenticatedPaymentStatusRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedResearchLabRoute: AuthenticatedResearchLabRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSignalHistoryRoute: AuthenticatedSignalHistoryRoute,
  AuthenticatedStrategyAnalyticsRoute: AuthenticatedStrategyAnalyticsRoute,
  AuthenticatedTelegramLogRoute: AuthenticatedTelegramLogRoute,
  AuthenticatedAdminAlertsRoute: AuthenticatedAdminAlertsRoute,
  AuthenticatedAdminBetaReadinessRoute: AuthenticatedAdminBetaReadinessRoute,
  AuthenticatedAdminCoindcxRoute: AuthenticatedAdminCoindcxRoute,
  AuthenticatedAdminGannGapRoute: AuthenticatedAdminGannGapRoute,
  AuthenticatedAdminInstitutionalFlowRoute:
    AuthenticatedAdminInstitutionalFlowRoute,
  AuthenticatedAdminLaunchReadinessRoute:
    AuthenticatedAdminLaunchReadinessRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
  AuthenticatedAdminReadinessRoute: AuthenticatedAdminReadinessRoute,
  AuthenticatedAdminReferralsRoute: AuthenticatedAdminReferralsRoute,
  AuthenticatedAdminResearchLabRoute: AuthenticatedAdminResearchLabRoute,
  AuthenticatedAdminStagingValidationRoute:
    AuthenticatedAdminStagingValidationRoute,
  AuthenticatedAdminSystemStatusRoute: AuthenticatedAdminSystemStatusRoute,
  AuthenticatedAdminTradingviewRoute: AuthenticatedAdminTradingviewRoute,
  AuthenticatedAdminWidgetsRoute: AuthenticatedAdminWidgetsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CryptoRouteChildren {
  CryptoPairRoute: typeof CryptoPairRoute
}

const CryptoRouteChildren: CryptoRouteChildren = {
  CryptoPairRoute: CryptoPairRoute,
}

const CryptoRouteWithChildren =
  CryptoRoute._addFileChildren(CryptoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AbsoluteIntradayRoute: AbsoluteIntradayRoute,
  AbsoluteIntradayValidationRoute: AbsoluteIntradayValidationRoute,
  AiDecisionCenterRoute: AiDecisionCenterRoute,
  AstroRoute: AstroRoute,
  AuthRoute: AuthRoute,
  BacktestRoute: BacktestRoute,
  BacktestingLabRoute: BacktestingLabRoute,
  BrokerRoute: BrokerRoute,
  CombinedPcrRoute: CombinedPcrRoute,
  CryptoRoute: CryptoRouteWithChildren,
  DecisionRoute: DecisionRoute,
  GannGapOutlookRoute: GannGapOutlookRoute,
  LiveLevelsRoute: LiveLevelsRoute,
  LiveMarketTerminalRoute: LiveMarketTerminalRoute,
  LiveTerminalRoute: LiveTerminalRoute,
  LoginRoute: LoginRoute,
  MarketBreadthRoute: MarketBreadthRoute,
  MarketReplayRoute: MarketReplayRoute,
  McpRoute: McpRoute,
  NewsRoute: NewsRoute,
  OptionStrategyRoute: OptionStrategyRoute,
  OptionsAnalyticsRoute: OptionsAnalyticsRoute,
  OptionsChainRoute: OptionsChainRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReleaseNotesRoute: ReleaseNotesRoute,
  RiskRoute: RiskRoute,
  SignalAccuracyRoute: SignalAccuracyRoute,
  StatusRoute: StatusRoute,
  StrategyBuilderRoute: StrategyBuilderRoute,
  TermsRoute: TermsRoute,
  WatchlistRoute: WatchlistRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DevAstroAuditRoute: DevAstroAuditRoute,
  DevAstroFixtureCaptureRoute: DevAstroFixtureCaptureRoute,
  DevDiagnosticsRoute: DevDiagnosticsRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksMorningBriefRoute: ApiPublicHooksMorningBriefRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
